// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mfcactivexctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CMfcactivexctrl1

IMPLEMENT_DYNCREATE(CMfcactivexctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMfcactivexctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CMfcactivexctrl1 operations
